language: python
install: echo "Nothing to install, $TRAVIS_TAG"
script: echo "Nothing to test" && true
before_deploy:
  - cd custom_components/shelly
  - zip -r shelly4hass .
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  tag_name: $TRAVIS_TAG
  name: $TRAVIS_TAG
  file: shelly4hass.zip
  skip_cleanup: true
  draft: true
  prerelease: true
  on:
    tags: true
    #condition: $TRAVIS_TAG =~ ^\d\.\d\.\d(-beta\.\d)?$
