blank_issues_enabled: false
contact_links:
  - name: Support and questions
    url: https://www.facebook.com/groups/419362892026600
    about: Please use our Facebook group for support and questions about ShellyForHass
